accept:
  - 渗透测试
  - 漏洞扫描
  - 代码审计
  - 软件测试
  - 系统测试
  - 第三方软件测试

borderline:
  - 风险评估
  - 验收测评
  - 验收测试
  - 第三方测评
  - 网络安全检测
  - 网络安全测评
  - 网络安全评估
  - 安全检测
  - 安全测评
  - 安全评估

reject:
  - 等级保护测评
  - 等保测评
  - 等级保护
  - 密评
  - 密码应用安全性评估
  - 商用密码应用安全性评估
  - 运维服务
  - 集约运维
  - 平台建设
